
async function fetchCreateTaskService() {
  try {
    const data = await ()=> { };

  } catch (error: any) {
    console.log("There was an Error" + error)
    throw new Error("System Error!")
  }
};
async function fetchReadTasks() {
  try {
    const data = await ()=> { };
  } catch (error: any) {
    console.log("There was an Error" + error)
    throw new Error("System Error!")
  }
};

async function fetchReadAllTasks() {
  try {
    const data = await ()=> { };
  } catch (error: any) {
    console.log("There was an Error" + error)
    throw new Error("System Error!")
  }
}



async function fetchUpdateTaskService() {
  try {
    const data = await ()=> { };
  } catch (error: any) {
    console.log("There was an Error" + error)
    throw new Error("System Error!")
  }
};
async function fetchDeleteTaskService() {
  try {
    const data = await ()=> { };
  } catch (error: any) {
    console.log("There was an Error" + error)
    throw new Error("System Error!")
  }
};

export {
  fetchCreateTaskService, fetchUpdateTaskService, fetchReadAllTasks, fetchReadTasks, fetchDeleteTaskService
}